### ISSUE TITLE
Feature request: Mute function

### ISSUE THREAD

**Issue by xZreai** [Digital-Flight-Dynamics/discord-bot#12]
Mute command is required with the appropriate time fixes - 1h, 2d etc

**Comment by Dynamic6448** [comment]
We would need a database to store mutes

**Comment by Dynamic6448** [comment]
I think it'd be best to use the built-in timeout feature rather than having to use a database for mutes

**Comment by devmeiko** [comment]
> I think it'd be best to use the built-in timeout feature rather than having to use a database for mutes

Yes, the timeout function is the best, muting usually doesn't work either due to role perms.
